## 导包

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'  #默认为'last'
%matplotlib inline

import numpy as np
import torch
import torch.nn as nn

import matplotlib.pyplot as plt
import pandas as pd
import time
import os
import sys
import random
from numpy import linalg
np.set_printoptions(threshold=np.inf, precision=2, suppress=True)

# torch.nn

In [7]:
l1 = nn.Linear(2,3,bias=True)
for n,v in l1.named_parameters():
    n
    v.shape

'weight'

torch.Size([3, 2])

'bias'

torch.Size([3])

In [8]:
a = torch.randn(3,2)
b = torch.randn(3,)
a
b


tensor([[ 0.0248,  0.5489],
        [ 1.3520, -2.0637],
        [-0.9140,  1.1142]])

tensor([0.2908, 0.9804, 0.0706])

## torch.nn.functional

### interpolate  
`torch.nn.functional.interpolate(input, size=None, scale_factor=None, mode='nearest', align_corners=None)`  
Parameters
* input (Tensor) – the input tensor

* size (python:int or Tuple[python:int] or Tuple[python:int, python:int] or Tuple[python:int, python:int, python:int]) – output spatial size.

* scale_factor (python:float or Tuple[python:float]) – multiplier for spatial size. Has to match input size if it is a tuple.

* mode (str) – algorithm used for upsampling: 'nearest' | 'linear' | 'bilinear' | 'bicubic' | 'trilinear' | 'area'. Default: 'nearest'

* align_corners (bool, optional) – Geometrically, we consider the pixels of the input and output as squares rather than points. If set to True, the input and output tensors are aligned by the center points of their corner pixels, preserving the values at the corner pixels. If set to False, the input and output tensors are aligned by the corner points of their corner pixels, and the interpolation uses edge value padding for out-of-boundary values, making this operation independent of input size when scale_factor is kept the same. This only has an effect when mode is 'linear', 'bilinear', 'bicubic' or 'trilinear'. Default: False

In [25]:
torch.set_printoptions(precision=2)
a=torch.arange(4.).reshape(1,2,2)
a
nn.functional.interpolate(a,scale_factor=2,mode='nearest')
a=torch.arange(8.).reshape(1,2,2,2)
a
nn.functional.interpolate(a,scale_factor=2,mode='nearest')


tensor([[[0., 1.],
         [2., 3.]]])

tensor([[[0., 0., 1., 1.],
         [2., 2., 3., 3.]]])

tensor([[[[0., 1.],
          [2., 3.]],

         [[4., 5.],
          [6., 7.]]]])

tensor([[[[0., 0., 1., 1.],
          [0., 0., 1., 1.],
          [2., 2., 3., 3.],
          [2., 2., 3., 3.]],

         [[4., 4., 5., 5.],
          [4., 4., 5., 5.],
          [6., 6., 7., 7.],
          [6., 6., 7., 7.]]]])

In [18]:
torch.set_printoptions(precision=2)
a=torch.arange(8.).reshape(1,2,2,2)
a=torch.arange(1,19.).reshape(1,2,3,3)
a
nn.functional.interpolate(a,scale_factor=2,mode='bilinear',align_corners=True)
nn.functional.interpolate(a,scale_factor=2,mode='bilinear',align_corners=False)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],

         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]])

tensor([[[[ 1.00,  1.40,  1.80,  2.20,  2.60,  3.00],
          [ 2.20,  2.60,  3.00,  3.40,  3.80,  4.20],
          [ 3.40,  3.80,  4.20,  4.60,  5.00,  5.40],
          [ 4.60,  5.00,  5.40,  5.80,  6.20,  6.60],
          [ 5.80,  6.20,  6.60,  7.00,  7.40,  7.80],
          [ 7.00,  7.40,  7.80,  8.20,  8.60,  9.00]],

         [[10.00, 10.40, 10.80, 11.20, 11.60, 12.00],
          [11.20, 11.60, 12.00, 12.40, 12.80, 13.20],
          [12.40, 12.80, 13.20, 13.60, 14.00, 14.40],
          [13.60, 14.00, 14.40, 14.80, 15.20, 15.60],
          [14.80, 15.20, 15.60, 16.00, 16.40, 16.80],
          [16.00, 16.40, 16.80, 17.20, 17.60, 18.00]]]])

tensor([[[[ 1.00,  1.25,  1.75,  2.25,  2.75,  3.00],
          [ 1.75,  2.00,  2.50,  3.00,  3.50,  3.75],
          [ 3.25,  3.50,  4.00,  4.50,  5.00,  5.25],
          [ 4.75,  5.00,  5.50,  6.00,  6.50,  6.75],
          [ 6.25,  6.50,  7.00,  7.50,  8.00,  8.25],
          [ 7.00,  7.25,  7.75,  8.25,  8.75,  9.00]],

         [[10.00, 10.25, 10.75, 11.25, 11.75, 12.00],
          [10.75, 11.00, 11.50, 12.00, 12.50, 12.75],
          [12.25, 12.50, 13.00, 13.50, 14.00, 14.25],
          [13.75, 14.00, 14.50, 15.00, 15.50, 15.75],
          [15.25, 15.50, 16.00, 16.50, 17.00, 17.25],
          [16.00, 16.25, 16.75, 17.25, 17.75, 18.00]]]])

[一文看懂align_corners](https://zhuanlan.zhihu.com/p/87572724)

### upsample(废弃，改用interpolate)

# torch.sparse

In [11]:
i = torch.LongTensor([[0, 1, 1], [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])
torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()

tensor([[0., 0., 3.],
        [4., 0., 5.]])

In [5]:
i = torch.LongTensor([[0, 2], [1, 0], [1, 2]])
v = torch.FloatTensor([3, 4, 5])
torch.sparse.FloatTensor(i.t(), v, torch.Size([2, 3])).to_dense()

tensor([[0., 0., 3.],
        [4., 0., 5.]])

In [6]:
i = torch.LongTensor([[2, 4]])
i
v = torch.FloatTensor([[1, 3], [5, 7]])
v
torch.sparse.FloatTensor(i, v)
torch.sparse.FloatTensor(i, v).to_dense()

tensor([[2, 4]])

tensor([[1., 3.],
        [5., 7.]])

tensor(indices=tensor([[2, 4]]),
       values=tensor([[1., 3.],
                      [5., 7.]]),
       size=(5, 2), nnz=2, layout=torch.sparse_coo)

tensor([[0., 0.],
        [0., 0.],
        [1., 3.],
        [0., 0.],
        [5., 7.]])

In [7]:
a = torch.randn(2, 3).to_sparse().requires_grad_(True)
a
a.to_dense()
# tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
#                        [0, 1, 2, 0, 1, 2]]),
#        values=tensor([ 1.5901,  0.0183, -0.6146,  1.8061, -0.0112,  0.6302]),
#        size=(2, 3), nnz=6, layout=torch.sparse_coo, requires_grad=True)

b = torch.randn(3, 2, requires_grad=True)
b
# tensor([[-0.6479,  0.7874],
#         [-1.2056,  0.5641],
#         [-1.1716, -0.9923]], requires_grad=True)

y = torch.sparse.mm(a, b)
y
# tensor([[-0.3323,  1.8723],
#         [-1.8951,  0.7904]], grad_fn=<SparseAddmmBackward>)
y.sum().backward()
a.grad
# tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
#                        [0, 1, 2, 0, 1, 2]]),
#        values=tensor([ 0.1394, -0.6415, -2.1639,  0.1394, -0.6415, -2.1639]),
#        size=(2, 3), nnz=6, layout=torch.sparse_coo)


tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
                       [0, 1, 2, 0, 1, 2]]),
       values=tensor([ 2.0876, -0.3764,  0.4160, -0.5974, -1.8790,  1.1513]),
       size=(2, 3), nnz=6, layout=torch.sparse_coo, requires_grad=True)

tensor([[ 2.0876, -0.3764,  0.4160],
        [-0.5974, -1.8790,  1.1513]], grad_fn=<ToDenseBackward>)

tensor([[ 2.1082,  0.7027],
        [ 1.6664,  0.8173],
        [-1.6953,  0.5092]], requires_grad=True)

tensor([[ 3.0686,  1.3711],
        [-6.3424, -1.3692]], grad_fn=<SparseAddmmBackward>)

tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
                       [0, 1, 2, 0, 1, 2]]),
       values=tensor([ 2.8109,  2.4837, -1.1860,  2.8109,  2.4837, -1.1860]),
       size=(2, 3), nnz=6, layout=torch.sparse_coo)

# API

## cat

In [5]:
a1=torch.Tensor([[1,2]])
a2=torch.Tensor([[3,4]])
a3=torch.Tensor([[5,6]])
a = (a1,a2,a3)
a
torch.cat(a)


(tensor([[1., 2.]]), tensor([[3., 4.]]), tensor([[5., 6.]]))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

# einsum

In [2]:
x = torch.randn(5)
y = torch.randn(4)
torch.einsum('i,j->ij', x, y)  # outer product
# tensor([[-0.0570, -0.0286, -0.0231,  0.0197],
#         [ 1.2616,  0.6335,  0.5113, -0.4351],
#         [ 1.4452,  0.7257,  0.5857, -0.4984],
#         [-0.4647, -0.2333, -0.1883,  0.1603],
#         [-1.1130, -0.5588, -0.4510,  0.3838]])


A = torch.randn(3,5,4)
l = torch.randn(2,5)
r = torch.randn(2,4)
torch.einsum('bn,anm,bm->ba', l, A, r) # compare torch.nn.functional.bilinear
# tensor([[-0.3430, -5.2405,  0.4494],
#         [ 0.3311,  5.5201, -3.0356]])


As = torch.randn(3,2,5)
Bs = torch.randn(3,5,4)
torch.einsum('bij,bjk->bik', As, Bs) # batch matrix multiplication
# tensor([[[-1.0564, -1.5904,  3.2023,  3.1271],
#          [-1.6706, -0.8097, -0.8025, -2.1183]],

#         [[ 4.2239,  0.3107, -0.5756, -0.2354],
#          [-1.4558, -0.3460,  1.5087, -0.8530]],

#         [[ 2.8153,  1.8787, -4.3839, -1.2112],
#          [ 0.3728, -2.1131,  0.0921,  0.8305]]])

A = torch.randn(3, 3)
torch.einsum('ii->i', A) # diagonal
# tensor([-0.7825,  0.8291, -0.1936])

A = torch.randn(4, 3, 3)
torch.einsum('...ii->...i', A) # batch diagonal
# tensor([[-1.0864,  0.7292,  0.0569],
#         [-0.9725, -1.0270,  0.6493],
#         [ 0.5832, -1.1716, -1.5084],
#         [ 0.4041, -1.1690,  0.8570]])

A = torch.randn(2, 3, 4, 5)
torch.einsum('...ij->...ji', A).shape # batch permute
# torch.Size([2, 3, 5, 4])

tensor([[ 1.3010,  0.1340, -2.2113, -0.6608],
        [ 0.7092,  0.0731, -1.2054, -0.3602],
        [-0.5546, -0.0571,  0.9426,  0.2817],
        [ 0.6613,  0.0681, -1.1240, -0.3359],
        [ 0.6079,  0.0626, -1.0333, -0.3088]])

tensor([[-0.6743,  0.2117, -0.1060],
        [-5.9914,  2.7196, -8.2246]])

tensor([[[-0.9479, -0.8942,  0.6105,  1.2177],
         [ 5.1920, -2.0442,  3.7597,  0.2774]],

        [[ 1.9755,  3.0665,  0.5966, -2.7625],
         [-1.7776, -4.3762, -0.1269, -1.9066]],

        [[ 1.1460,  1.0215, -0.8949,  1.3821],
         [-0.1486, -1.9964,  1.4362, -0.9691]]])

tensor([-0.5741,  0.7686, -1.5141])

tensor([[-0.9746, -1.4177, -1.3442],
        [-0.2116,  0.5845,  0.7181],
        [ 0.2219, -0.7531,  1.5207],
        [-0.9117, -1.1787,  0.6000]])

torch.Size([2, 3, 5, 4])

In [38]:
a = torch.arange(24).reshape(2,3,4)
b = torch.arange(12).reshape(3,2,2)
b = torch.ones(3,2,2)
a
b
# torch.einsum('bij,bjk', a, b）
c = torch.einsum('ij...,jkl->ijkl', a, b)
c
c.shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

tensor([[[[ 6.,  6.],
          [ 6.,  6.]],

         [[22., 22.],
          [22., 22.]],

         [[38., 38.],
          [38., 38.]]],


        [[[54., 54.],
          [54., 54.]],

         [[70., 70.],
          [70., 70.]],

         [[86., 86.],
          [86., 86.]]]])

torch.Size([2, 3, 2, 2])

In [59]:
a = torch.arange(24.).reshape(2,2,3,2)
# b = torch.arange(12).reshape(3,2,2)
b = torch.Tensor([1,2]).repeat(2, 3, 2)
a
b
c = torch.einsum('bij...,bjk->bijk', a, b)
# c = torch.einsum('ij,jk->ik', a, b)
c
c.shape

tensor([[[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],

         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]],


        [[[12., 13.],
          [14., 15.],
          [16., 17.]],

         [[18., 19.],
          [20., 21.],
          [22., 23.]]]])

tensor([[[1., 2., 1., 2.],
         [1., 2., 1., 2.],
         [1., 2., 1., 2.]],

        [[1., 2., 1., 2.],
         [1., 2., 1., 2.],
         [1., 2., 1., 2.]]])

tensor([[[[ 1.,  2.,  1.,  2.],
          [ 5., 10.,  5., 10.],
          [ 9., 18.,  9., 18.]],

         [[13., 26., 13., 26.],
          [17., 34., 17., 34.],
          [21., 42., 21., 42.]]],


        [[[25., 50., 25., 50.],
          [29., 58., 29., 58.],
          [33., 66., 33., 66.]],

         [[37., 74., 37., 74.],
          [41., 82., 41., 82.],
          [45., 90., 45., 90.]]]])

torch.Size([2, 2, 3, 4])

In [44]:
help(a.repeat)

Help on built-in function repeat:

repeat(...) method of torch.Tensor instance
    repeat(*sizes) -> Tensor
    
    Repeats this tensor along the specified dimensions.
    
    Unlike :meth:`~Tensor.expand`, this function copies the tensor's data.
    
    .. warning::
    
        :func:`torch.repeat` behaves differently from
        `numpy.repeat <https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html>`_,
        but is more similar to
        `numpy.tile <https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html>`_.
        For the operator similar to `numpy.repeat`, see :func:`torch.repeat_interleave`.
    
    Args:
        sizes (torch.Size or int...): The number of times to repeat this tensor along each
            dimension
    
    Example::
    
        >>> x = torch.tensor([1, 2, 3])
        >>> x.repeat(4, 2)
        tensor([[ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2,  3],
             

# Prune


In [2]:
import torch
from torch import nn
import torch.nn.utils.prune as prune
import torch.nn.functional as F

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square conv kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5x5 image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, int(x.nelement() / x.shape[0]))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

model = LeNet().to(device=device)

In [4]:
module = model.conv1
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.0676,  0.2664, -0.1045],
          [-0.0686,  0.0935,  0.2987],
          [ 0.3007,  0.2398,  0.1515]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.2507, -0.1184],
          [-0.1625, -0.1486, -0.1400]]],


        [[[ 0.2331, -0.2785, -0.1710],
          [ 0.0477, -0.2853,  0.2136],
          [-0.3326,  0.2331, -0.3113]]],


        [[[ 0.1029, -0.0356, -0.2184],
          [ 0.1442,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0256, -0.0950, -0.1283],
          [ 0.1312, -0.3005,  0.2354],
          [-0.0945,  0.0965,  0.0685]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.2479,  0.2989, -0.0678],
          [-0.0997,  0.1652,  0.1718]]]], requires_grad=True)), ('bias', Parameter containing:
tensor([-0.1904,  0.1956,  0.0284, -0.1526, -0.1712,  0.3311],
       requires_grad=True))]


In [5]:
print(list(module.named_buffers()))

[]


In [6]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

In [8]:
print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([-0.1904,  0.1956,  0.0284, -0.1526, -0.1712,  0.3311],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 0.0676,  0.2664, -0.1045],
          [-0.0686,  0.0935,  0.2987],
          [ 0.3007,  0.2398,  0.1515]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.2507, -0.1184],
          [-0.1625, -0.1486, -0.1400]]],


        [[[ 0.2331, -0.2785, -0.1710],
          [ 0.0477, -0.2853,  0.2136],
          [-0.3326,  0.2331, -0.3113]]],


        [[[ 0.1029, -0.0356, -0.2184],
          [ 0.1442,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0256, -0.0950, -0.1283],
          [ 0.1312, -0.3005,  0.2354],
          [-0.0945,  0.0965,  0.0685]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.2479,  0.2989, -0.0678],
          [-0.0997,  0.1652,  0.1718]]]], requires_grad=True))]


In [9]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 1., 1.],
          [0., 1., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 0., 0.],
          [1., 0., 1.]]],


        [[[0., 0., 0.],
          [0., 1., 1.],
          [0., 0., 0.]]],


        [[[1., 1., 0.],
          [0., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [0., 0., 0.],
          [0., 1., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [0., 0., 0.]]]]))]


In [10]:
print(module.weight)

tensor([[[[ 0.0000,  0.2664, -0.1045],
          [-0.0000,  0.0935,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.0000, -0.0000],
          [-0.1625, -0.0000, -0.1400]]],


        [[[ 0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.2853,  0.2136],
          [-0.0000,  0.0000, -0.0000]]],


        [[[ 0.1029, -0.0356, -0.0000],
          [ 0.0000,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0256, -0.0950, -0.1283],
          [ 0.0000, -0.0000,  0.0000],
          [-0.0000,  0.0965,  0.0000]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.0000,  0.2989, -0.0678],
          [-0.0000,  0.0000,  0.0000]]]], grad_fn=<MulBackward0>)


In [11]:
print(module._forward_pre_hooks)

OrderedDict([(1, <torch.nn.utils.prune.PruningContainer object at 0x7fc11290afa0>)])


In [12]:
prune.l1_unstructured(module, name="bias", amount=3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

In [13]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0676,  0.2664, -0.1045],
          [-0.0686,  0.0935,  0.2987],
          [ 0.3007,  0.2398,  0.1515]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.2507, -0.1184],
          [-0.1625, -0.1486, -0.1400]]],


        [[[ 0.2331, -0.2785, -0.1710],
          [ 0.0477, -0.2853,  0.2136],
          [-0.3326,  0.2331, -0.3113]]],


        [[[ 0.1029, -0.0356, -0.2184],
          [ 0.1442,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0256, -0.0950, -0.1283],
          [ 0.1312, -0.3005,  0.2354],
          [-0.0945,  0.0965,  0.0685]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.2479,  0.2989, -0.0678],
          [-0.0997,  0.1652,  0.1718]]]], requires_grad=True)), ('bias_orig', Parameter containing:
tensor([-0.1904,  0.1956,  0.0284, -0.1526, -0.1712,  0.3311],
       requires_grad=True))]


In [14]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 1., 1.],
          [0., 1., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 0., 0.],
          [1., 0., 1.]]],


        [[[0., 0., 0.],
          [0., 1., 1.],
          [0., 0., 0.]]],


        [[[1., 1., 0.],
          [0., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [0., 0., 0.],
          [0., 1., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [0., 0., 0.]]]])), ('bias_mask', tensor([1., 1., 0., 0., 0., 1.]))]


In [15]:
print(module.bias)

tensor([-0.1904,  0.1956,  0.0000, -0.0000, -0.0000,  0.3311],
       grad_fn=<MulBackward0>)


In [16]:
print(module._forward_pre_hooks)

OrderedDict([(1, <torch.nn.utils.prune.PruningContainer object at 0x7fc11290afa0>), (2, <torch.nn.utils.prune.L1Unstructured object at 0x7fc1128fcd60>)])


In [17]:
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

# As we can verify, this will zero out all the connections corresponding to
# 50% (3 out of 6) of the channels, while preserving the action of the
# previous mask.
print(module.weight)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

tensor([[[[ 0.0000,  0.0000, -0.0000],
          [-0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.0000, -0.0000],
          [-0.1625, -0.0000, -0.1400]]],


        [[[ 0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [-0.0000,  0.0000, -0.0000]]],


        [[[ 0.1029, -0.0356, -0.0000],
          [ 0.0000,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [-0.0000,  0.0000,  0.0000]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.0000,  0.2989, -0.0678],
          [-0.0000,  0.0000,  0.0000]]]], grad_fn=<MulBackward0>)


In [18]:
for hook in module._forward_pre_hooks.values():
    if hook._tensor_name == "weight":  # select out the correct hook
        break

print(list(hook))  # pruning history in the container

[<torch.nn.utils.prune.RandomUnstructured object at 0x7fc1128fc610>, <torch.nn.utils.prune.RandomUnstructured object at 0x7fc11290ad00>, <torch.nn.utils.prune.LnStructured object at 0x7fc11290a910>]


## Serializing a pruned model

In [19]:
print(model.state_dict().keys())

odict_keys(['conv1.weight_orig', 'conv1.bias_orig', 'conv1.weight_mask', 'conv1.bias_mask', 'conv2.weight', 'conv2.bias', 'fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias'])


In [20]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0676,  0.2664, -0.1045],
          [-0.0686,  0.0935,  0.2987],
          [ 0.3007,  0.2398,  0.1515]]],


        [[[-0.2550, -0.0591, -0.1830],
          [ 0.0049, -0.2507, -0.1184],
          [-0.1625, -0.1486, -0.1400]]],


        [[[ 0.2331, -0.2785, -0.1710],
          [ 0.0477, -0.2853,  0.2136],
          [-0.3326,  0.2331, -0.3113]]],


        [[[ 0.1029, -0.0356, -0.2184],
          [ 0.1442,  0.1608, -0.2759],
          [ 0.2694, -0.1319, -0.1092]]],


        [[[ 0.0256, -0.0950, -0.1283],
          [ 0.1312, -0.3005,  0.2354],
          [-0.0945,  0.0965,  0.0685]]],


        [[[ 0.2051,  0.2528, -0.0950],
          [-0.2479,  0.2989, -0.0678],
          [-0.0997,  0.1652,  0.1718]]]], requires_grad=True)), ('bias_orig', Parameter containing:
tensor([-0.1904,  0.1956,  0.0284, -0.1526, -0.1712,  0.3311],
       requires_grad=True))]


In [21]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 0., 0.],
          [1., 0., 1.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 0.],
          [0., 1., 1.],
          [1., 1., 1.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [0., 0., 0.]]]])), ('bias_mask', tensor([1., 1., 0., 0., 0., 1.]))]


In [42]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

ValueError: Parameter 'weight' of module Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1)) has to be pruned before pruning can be removed

In [23]:
print(list(module.named_buffers()))

[('bias_mask', tensor([1., 1., 0., 0., 0., 1.]))]


## Pruning multiple parameters in a model

In [88]:
new_model = LeNet()
# new_model.save("./save/a.pt")
torch.save(new_model, "./save/a.pt")
# new_model2 = new_model.clone()
# 400*120
a = torch.randn(1,1,28,28)

b = new_model(a)
b.shape
# for n, p in new_model.named_parameters():
#     n, p.shape
# for n, p in new_model.named_modules():
#     n
#     p

torch.Size([1, 10])

In [70]:
%%timeit
b = new_model(a)

607 µs ± 49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [89]:

for name, module in new_model.named_modules():
    # prune 20% of connections in all 2D-conv layers
    if isinstance(module, torch.nn.Conv2d):
        prune.l1_unstructured(module, name='weight', amount=0.6)
    # prune 40% of connections in all linear layers
    elif isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.4)

print(dict(new_model.named_buffers()).keys())  # to verify that all masks exist

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))

Linear(in_features=400, out_features=120, bias=True)

Linear(in_features=120, out_features=84, bias=True)

Linear(in_features=84, out_features=10, bias=True)

dict_keys(['conv1.weight_mask', 'conv2.weight_mask', 'fc1.weight_mask', 'fc2.weight_mask', 'fc3.weight_mask'])


In [29]:
print(list(new_model.named_parameters()))

[('conv1.bias', Parameter containing:
tensor([-0.2661, -0.1464,  0.1981, -0.2879,  0.1437,  0.3165],
       requires_grad=True)), ('conv1.weight_orig', Parameter containing:
tensor([[[[-0.0526, -0.1373,  0.2569],
          [-0.0020, -0.2266,  0.2198],
          [-0.3097,  0.1792, -0.3308]]],


        [[[-0.3077,  0.0166,  0.1194],
          [ 0.1629,  0.1295,  0.0457],
          [ 0.2685, -0.0435, -0.1927]]],


        [[[-0.0340, -0.0738, -0.1328],
          [-0.1415, -0.2674,  0.0236],
          [ 0.2277, -0.0227,  0.1259]]],


        [[[ 0.1886,  0.0692,  0.1732],
          [ 0.2386, -0.0198, -0.2122],
          [-0.2701,  0.0327, -0.2260]]],


        [[[ 0.3324, -0.0460,  0.2436],
          [-0.1378, -0.3200,  0.1307],
          [-0.1458, -0.0168,  0.0722]]],


        [[[ 0.1197, -0.0244, -0.0780],
          [ 0.2695,  0.2498,  0.2103],
          [-0.1643, -0.0130, -0.2759]]]], requires_grad=True)), ('conv2.bias', Parameter containing:
tensor([-0.0796,  0.1039, -0.0753,  0.0784

In [32]:
prune.remove(new_model, 'weight')

ValueError: Parameter 'weight' of module LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
) has to be pruned before pruning can be removed

In [90]:
for name, module in new_model.named_modules():
#     print(name)
#     print(hasattr(module, "weight"))
    if hasattr(module, "weight"):
        prune.remove(module, 'weight')

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))

Linear(in_features=400, out_features=120, bias=True)

Linear(in_features=120, out_features=84, bias=True)

Linear(in_features=84, out_features=10, bias=True)

In [71]:
%%timeit
b = new_model(a)

621 µs ± 65.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [74]:
for name, module in new_model.named_modules():
    print(name)
    print(module)


LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
conv1
Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
conv2
Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
fc1
Linear(in_features=400, out_features=120, bias=True)
fc2
Linear(in_features=120, out_features=84, bias=True)
fc3
Linear(in_features=84, out_features=10, bias=True)


In [91]:
print(list(new_model.named_parameters()))

[('conv1.bias', Parameter containing:
tensor([-0.0548,  0.0290, -0.0349,  0.0005,  0.2851,  0.1343],
       requires_grad=True)), ('conv1.weight', Parameter containing:
tensor([[[[ 0.0000,  0.0000, -0.0000],
          [-0.2591,  0.0000, -0.0000],
          [-0.1820, -0.1879,  0.3151]]],


        [[[-0.1805,  0.2011,  0.2644],
          [-0.0000,  0.0000, -0.0000],
          [-0.2450,  0.0000,  0.2964]]],


        [[[-0.0000,  0.0000, -0.0000],
          [-0.0000, -0.3274,  0.0000],
          [ 0.3038, -0.3070, -0.0000]]],


        [[[ 0.2814,  0.0000, -0.2850],
          [-0.0000, -0.0000, -0.2134],
          [-0.3121,  0.0000, -0.2524]]],


        [[[-0.0000,  0.0000,  0.2947],
          [-0.0000, -0.0000,  0.0000],
          [-0.0000,  0.0000, -0.0000]]],


        [[[-0.2175,  0.2236, -0.0000],
          [-0.1700, -0.0000, -0.1669],
          [ 0.0000, -0.0000, -0.0000]]]], requires_grad=True)), ('conv2.bias', Parameter containing:
tensor([ 0.1171,  0.0828,  0.0715,  0.0084, -0.

In [92]:
torch.save(new_model, "./save/b.pt")

## Global pruning

In [25]:
model = LeNet()

parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.conv2, 'weight'),
    (model.fc1, 'weight'),
    (model.fc2, 'weight'),
    (model.fc3, 'weight'),
)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

In [26]:
print(
    "Sparsity in conv1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv1.weight == 0))
        / float(model.conv1.weight.nelement())
    )
)
print(
    "Sparsity in conv2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv2.weight == 0))
        / float(model.conv2.weight.nelement())
    )
)
print(
    "Sparsity in fc1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc1.weight == 0))
        / float(model.fc1.weight.nelement())
    )
)
print(
    "Sparsity in fc2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc2.weight == 0))
        / float(model.fc2.weight.nelement())
    )
)
print(
    "Sparsity in fc3.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc3.weight == 0))
        / float(model.fc3.weight.nelement())
    )
)
print(
    "Global sparsity: {:.2f}%".format(
        100. * float(
            torch.sum(model.conv1.weight == 0)
            + torch.sum(model.conv2.weight == 0)
            + torch.sum(model.fc1.weight == 0)
            + torch.sum(model.fc2.weight == 0)
            + torch.sum(model.fc3.weight == 0)
        )
        / float(
            model.conv1.weight.nelement()
            + model.conv2.weight.nelement()
            + model.fc1.weight.nelement()
            + model.fc2.weight.nelement()
            + model.fc3.weight.nelement()
        )
    )
)

Sparsity in conv1.weight: 1.85%
Sparsity in conv2.weight: 7.41%
Sparsity in fc1.weight: 22.05%
Sparsity in fc2.weight: 12.25%
Sparsity in fc3.weight: 10.00%
Global sparsity: 20.00%


## Extending torch.nn.utils.prune with custom pruning functions

In [80]:
class FooBarPruningMethod(prune.BasePruningMethod):
    """Prune every other entry in a tensor
    """
    PRUNING_TYPE = 'unstructured'

    def compute_mask(self, t, default_mask):
        mask = default_mask.clone()
        mask.view(-1)[::2] = 0
        return mask

In [81]:
def foobar_unstructured(module, name):
    """Prunes tensor corresponding to parameter called `name` in `module`
    by removing every other entry in the tensors.
    Modifies module in place (and also return the modified module)
    by:
    1) adding a named buffer called `name+'_mask'` corresponding to the
    binary mask applied to the parameter `name` by the pruning method.
    The parameter `name` is replaced by its pruned version, while the
    original (unpruned) parameter is stored in a new parameter named
    `name+'_orig'`.

    Args:
        module (nn.Module): module containing the tensor to prune
        name (string): parameter name within `module` on which pruning
                will act.

    Returns:
        module (nn.Module): modified (i.e. pruned) version of the input
            module

    Examples:
        >>> m = nn.Linear(3, 4)
        >>> foobar_unstructured(m, name='bias')
    """
    FooBarPruningMethod.apply(module, name)
    return module

In [85]:
model = LeNet()
foobar_unstructured(model.fc3, name='bias')
# print(model.fc3.weights_mask)
print(model.fc3.bias_mask)

Linear(in_features=84, out_features=10, bias=True)

tensor([0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])


# QUANTIZATION

In [104]:
import torch

# define a floating point model
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.fc = torch.nn.Linear(4, 4)

    def forward(self, x):
        x = self.fc(x)
        return x

# create a model instance
model_fp32 = M()
# create a quantized model instance
model_int8 = torch.quantization.quantize_dynamic(
    model_fp32,  # the original model
    {torch.nn.Linear},  # a set of layers to dynamically quantize
    dtype=torch.qint8)  # the target dtype for quantized weights

# run the model
input_fp32 = torch.randn(4, 4, 4, 4)
res = model_int8(input_fp32)

In [106]:
a = torch.randn(4,4,4,4)

In [113]:
%%timeit
b = model_fp32(a)

72.9 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [111]:
torch.save(model_fp32, "./save/a.pt")
flops1, params1 = profile(model_fp32, inputs=(a, ))
flops1
params1

[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class '__main__.M'>. Treat it as zero Macs and zero Params.


1024.0

20.0

In [114]:
%%timeit
# run the model
input_fp32 = torch.randn(4, 4, 4, 4)
res = model_int8(input_fp32)

93.4 µs ± 10 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [112]:
torch.save(model_int8, "./save/b.pt")
flops2, params2 = profile(model_int8, inputs=(input_fp32, ))
flops2
params2

[WARN] Cannot find rule for <class 'torch.nn.quantized.modules.linear.LinearPackedParams'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.quantized.dynamic.modules.linear.Linear'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class '__main__.M'>. Treat it as zero Macs and zero Params.


0

0

In [129]:
import torch

# define a floating point model where some layers could be statically quantized
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        # QuantStub converts tensors from floating point to quantized
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(1, 1, 3,1,1)
        self.relu = torch.nn.ReLU()
        # DeQuantStub converts tensors from quantized to floating point
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        # manually specify where tensors will be converted from floating
        # point to quantized in the quantized model
        x = self.quant(x)
        x = self.conv(x)
        x = self.relu(x)
        # manually specify where tensors will be converted from quantized
        # to floating point in the quantized model
        x = self.dequant(x)
        return x

# create a model instance
model_fp32 = M()

# model must be set to eval mode for static quantization logic to work
model_fp32.eval()

# attach a global qconfig, which contains information about what kind
# of observers to attach. Use 'fbgemm' for server inference and
# 'qnnpack' for mobile inference. Other quantization configurations such
# as selecting symmetric or assymetric quantization and MinMax or L2Norm
# calibration techniques can be specified here.
model_fp32.qconfig = torch.quantization.get_default_qconfig('fbgemm')

# Fuse the activations to preceding layers, where applicable.
# This needs to be done manually depending on the model architecture.
# Common fusions include `conv + relu` and `conv + batchnorm + relu`
model_fp32_fused = torch.quantization.fuse_modules(model_fp32, [['conv', 'relu']])

# Prepare the model for static quantization. This inserts observers in
# the model that will observe activation tensors during calibration.
model_fp32_prepared = torch.quantization.prepare(model_fp32_fused)

# calibrate the prepared model to determine quantization parameters for activations
# in a real world setting, the calibration would be done with a representative dataset
input_fp32 = torch.randn(4, 1, 4, 4)
t1 = time.time()
r1 = model_fp32_prepared(input_fp32)
t2 = time.time()
t2 - t1
r1
# r2 = model_fp32_fused(input_fp32)
# r2
# Convert the observed model to a quantized model. This does several things:
# quantizes the weights, computes and stores the scale and bias value to be
# used with each activation tensor, and replaces key operators with quantized
# implementations.
model_int8 = torch.quantization.convert(model_fp32_prepared)

# run the model, relevant calculations will happen in int8
t1 = time.time()
res = model_int8(input_fp32)
t2 = time.time()
t2 - t1
res

M(
  (quant): QuantStub()
  (conv): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu): ReLU()
  (dequant): DeQuantStub()
)

/home/wen/.local/lib/python3.8/site-packages/torch/quantization/observer.py:119: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(


0.022613525390625

tensor([[[[0.1629, 0.2210, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.6361, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 1.2354, 0.0000],
          [0.6028, 0.0540, 0.0000, 0.1846],
          [0.0000, 0.0000, 1.3695, 0.0000],
          [0.1652, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.4022, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.7971, 0.5657],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000, 0.0000],
          [0.3361, 0.5855, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.1967, 0.2293],
          [0.3332, 0.0000, 0.0000, 0.0000]]]], grad_fn=<ReluBackward0>)

0.0030586719512939453

tensor([[[[0.1617, 0.2263, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.6359, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 1.2287, 0.0000],
          [0.5928, 0.0431, 0.0000, 0.1940],
          [0.0000, 0.0000, 1.3473, 0.0000],
          [0.1617, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.3988, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.7976, 0.5605],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000, 0.0000],
          [0.3341, 0.5820, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.1940, 0.2371],
          [0.3341, 0.0000, 0.0000, 0.0000]]]])

In [130]:
for n, p in model_int8.named_parameters():
    n, p

In [131]:
for n, p in model_fp32.named_parameters():
    n, p

('conv.weight',
 Parameter containing:
 tensor([[[[ 0.2498, -0.0528, -0.2379],
           [-0.1591,  0.0134,  0.1101],
           [ 0.3073, -0.2695, -0.3309]]]], requires_grad=True))

('conv.bias',
 Parameter containing:
 tensor([-0.1820], requires_grad=True))

In [134]:
import torch

# define a floating point model where some layers could benefit from QAT
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        # QuantStub converts tensors from floating point to quantized
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(1, 1, 1)
        self.bn = torch.nn.BatchNorm2d(1)
        self.relu = torch.nn.ReLU()
        # DeQuantStub converts tensors from quantized to floating point
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        x = self.dequant(x)
        return x

# create a model instance
model_fp32 = M()

# model must be set to train mode for QAT logic to work
model_fp32.train()

# attach a global qconfig, which contains information about what kind
# of observers to attach. Use 'fbgemm' for server inference and
# 'qnnpack' for mobile inference. Other quantization configurations such
# as selecting symmetric or assymetric quantization and MinMax or L2Norm
# calibration techniques can be specified here.
model_fp32.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')

# fuse the activations to preceding layers, where applicable
# this needs to be done manually depending on the model architecture
model_fp32_fused = torch.quantization.fuse_modules(model_fp32,
    [['conv', 'bn', 'relu']])

# Prepare the model for QAT. This inserts observers and fake_quants in
# the model that will observe weight and activation tensors during calibration.
model_fp32_prepared = torch.quantization.prepare_qat(model_fp32_fused)

# run the training loop (not shown)
# training_loop(model_fp32_prepared)

# Convert the observed model to a quantized model. This does several things:
# quantizes the weights, computes and stores the scale and bias value to be
# used with each activation tensor, fuses modules where appropriate,
# and replaces key operators with quantized implementations.
model_fp32_prepared.eval()
model_int8 = torch.quantization.convert(model_fp32_prepared)

# run the model, relevant calculations will happen in int8
res = model_int8(input_fp32)
res

M(
  (quant): QuantStub()
  (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
  (bn): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU()
  (dequant): DeQuantStub()
)

/home/wen/.local/lib/python3.8/site-packages/torch/quantization/observer.py:119: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(


M(
  (quant): QuantStub(
    (activation_post_process): FakeQuantize(
      fake_quant_enabled=tensor([1], dtype=torch.uint8), observer_enabled=tensor([1], dtype=torch.uint8),            quant_min=0, quant_max=255, dtype=torch.quint8, qscheme=torch.per_tensor_affine, ch_axis=-1,         scale=tensor([1.]), zero_point=tensor([0])
      (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
    )
  )
  (conv): ConvBnReLU2d(
    1, 1, kernel_size=(1, 1), stride=(1, 1)
    (bn): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (weight_fake_quant): FakeQuantize(
      fake_quant_enabled=tensor([1], dtype=torch.uint8), observer_enabled=tensor([1], dtype=torch.uint8),            quant_min=-128, quant_max=127, dtype=torch.qint8, qscheme=torch.per_channel_symmetric, ch_axis=0,         scale=tensor([1.]), zero_point=tensor([0])
      (activation_post_process): MovingAveragePerChannelMinMaxObserver(min_val=tensor([]), max_val=tensor([])

/home/wen/.local/lib/python3.8/site-packages/torch/quantization/observer.py:241: UserWarning: must run observer before calling calculate_qparams.                                        Returning default scale and zero point 
  warnings.warn(


tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

# thop

In [94]:
from torchvision.models import resnet50
from thop import profile
model = resnet50()
input = torch.randn(1, 3, 224, 224)
flops, params = profile(model, inputs=(input, ))

[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_bn() for <class 'torch.nn.modules.batchnorm.BatchNorm2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.activation.ReLU'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pooling.MaxPool2d'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torchvision.models.resnet.Bottleneck'>. Treat it as zero Macs and zero Params.
[INFO] Register count_adap_avgpool() for <class 'torch.nn.modules.pooling.AdaptiveAvgPool2d'>.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class 'torchvision.models.resnet.ResNet'>. Treat it as zero Macs and zero Params.


In [103]:
class YourModule(nn.Module):
    # your definition
    def __init__(self):
        super(YourModule, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square conv kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5x5 image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, int(x.nelement() / x.shape[0]))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
# def count_your_model(model, x, y):
    # your rule here
model = YourModule()
x = torch.randn(1, 1, 28, 28)
# flops, params = profile(model, inputs=(input, ), 
#                         custom_ops={YourModule: count_your_model})
flops, params = profile(model, inputs=(x, ), verbose=True)
flops
params

[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class '__main__.YourModule'>. Treat it as zero Macs and zero Params.


205960.0

60074.0

In [99]:
from thop import clever_format
flops, params = clever_format([flops, params], "%.3f")

In [100]:
flops
params

'205.960K'

'60.074K'

In [101]:
n = 0
for name, param in model.named_parameters():
    n += param.view(-1).shape[0]
n

60074

# freetest

In [28]:
a = torch.randn(3,3)
a.nelement()
a.numel()

9

9

In [141]:
import torch
a = [
    [2, 3, 4, 5, 0, 0],
    [1, 4, 3, 0, 0, 0],
    [4, 2, 2, 5, 7, 0],
    [1, 0, 0, 0, 0, 0]
]
a = torch.tensor(input)
#注意index的类型
length = torch.LongTensor([[4],[3],[5],[1]])
length.shape
#index之所以减1,是因为序列维度是从0开始计算的
out = torch.gather(a, 1, length-1)
out


<ipython-input-141-ad7aa0f51e8c>:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(input)


torch.Size([4, 1])

tensor([[5],
        [3],
        [7],
        [1]])

In [156]:
a = torch.arange(8).reshape(2,2,2)
a

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [161]:
# idx = torch.LongTensor([0,1]).reshape(-1,1)
idx = torch.randint(0,2,(2,1,2))
idx
a.shape
idx.shape
b = torch.gather(a, 1, idx)
b

SyntaxError: invalid syntax (<ipython-input-161-623c49eea11d>, line 7)

In [151]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0, 1], [1, 0, 1]]))

tensor([[1, 1, 2],
        [4, 3, 4]])

# end