## 导包

In [68]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'  #默认为'last'
%matplotlib inline

import numpy as np
import tensorflow as tf
import torch

import matplotlib.pyplot as plt
import pandas as pd
import time
import os
import sys
import random
from numpy import linalg
np.set_printoptions(threshold=np.inf, precision=2, suppress=True)

# API

## 变量

### constant

In [6]:
tf.constant([1])
tf.constant([2.2],dtype=tf.float32)
tf.constant([1.1])
tf.constant([1,2,3,4],shape=(2,2))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.2], dtype=float32)>

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.1], dtype=float32)>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### device

In [31]:
a1 = tf.constant([1.0])
# a.device
a1.gpu(0)
a1.device

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

'/job:localhost/replica:0/task:0/device:CPU:0'

In [18]:
with tf.device('gpu'):
    a1 = tf.constant([1.0])
a1.device
a1

'/job:localhost/replica:0/task:0/device:GPU:0'

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

### ndim

In [21]:
a = tf.constant([1,2,3,4],shape=(2,2))
a.ndim

2

### rank

In [44]:
a1 = tf.constant([1,2,3,4],shape=(2,2)).gpu()
tf.rank(a1)
a1.device
a1= a1.cpu()
a1.device

<tf.Tensor: shape=(), dtype=int32, numpy=2>

'/job:localhost/replica:0/task:0/device:GPU:0'

'/job:localhost/replica:0/task:0/device:CPU:0'

In [40]:
a2 = tf.constant([1.1])
a2 = a2.gpu(0)
a2.device

'/job:localhost/replica:0/task:0/device:GPU:0'

### range()

In [17]:
tf.range(4) # torch.arange

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

### numpy()

In [20]:
a1 = tf.constant([1.0])
a1
a1.numpy()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

array([1.], dtype=float32)

In [75]:
tf.zeros([2,2])
tf.ones([2,2])
tf.zeros([])
tf.ones([])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [153]:
tf.fill([2,3,3],2)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])>

## convert

### convert_to_tensor

In [47]:
a = np.arange(9).reshape(3,3)
a
tf.convert_to_tensor(a)
tf.convert_to_tensor(a,dtype=tf.float32)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [71]:
tf.convert_to_tensor([1,2,3,4.])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

### cast
转换数据类型

In [53]:
a = tf.constant([1,2,3,4])
a
tf.cast(a,dtype=tf.double)
a


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [57]:
a = tf.constant([1,0,0,1])
a
a1 = tf.cast(a,dtype=tf.bool)
a1
# a1+a1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 0, 1])>

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False,  True])>

## Variable

### tf.Variable

In [61]:
a = tf.constant([1,2,3,4])
b = tf.Variable(a)
a
b
isinstance(b,tf.Variable)
isinstance(a,tf.Tensor)
tf.is_tensor(b)
b.numpy()

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

True

True

True

array([1, 2, 3, 4])

### 标量

In [64]:
a = tf.ones([])
a
a.numpy()
int(a)
float(a)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

1.0

1

1.0

In [70]:
# pytorh类似
a = torch.ones([])
a
a.numpy()
a.shape
float(a)

tensor(1.)

array(1., dtype=float32)

torch.Size([])

1.0

## random

In [76]:
tf.random.normal([3,3],mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.09,  0.11, -1.09],
       [-0.08, -0.92, -0.91],
       [-0.32, -1.22, -0.68]], dtype=float32)>

In [78]:
tf.random.uniform([3,3])
tf.random.uniform([3,3],1,2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.02, 0.01, 0.11],
       [0.51, 0.7 , 0.1 ],
       [0.72, 0.6 , 0.33]], dtype=float32)>

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.71, 1.69, 1.49],
       [1.62, 1.92, 1.45],
       [1.11, 1.22, 1.99]], dtype=float32)>

### 截断分布

In [79]:
tf.random.truncated_normal([3,3],mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.62,  0.49,  0.51],
       [ 1.15, -0.12,  0.6 ],
       [-1.28,  0.77, -0.14]], dtype=float32)>

### 打散

In [87]:
a = tf.range(9)
a
tf.random.shuffle(a)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([6, 1, 8, 2, 4, 7, 0, 5, 3])>

In [92]:
a = tf.random.normal([10,3])
b = tf.random.uniform([10,],0,10,dtype=tf.int64)
idx = tf.random.shuffle(tf.range(10))
a
b
idx
tf.gather(a,idx)
tf.gather(b,idx)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[ 2.06,  0.09,  1.1 ],
       [ 0.27, -0.2 , -0.66],
       [ 0.78,  0.38,  1.  ],
       [ 0.05,  0.52,  0.15],
       [ 1.37, -0.91,  1.24],
       [ 3.26, -0.9 , -1.39],
       [-0.22,  1.49,  0.69],
       [-1.04,  0.91,  0.48],
       [ 0.56, -0.65,  0.99],
       [-0.22, -0.68, -1.4 ]], dtype=float32)>

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 5, 1, 1, 3, 6, 7, 6, 0, 6], dtype=int64)>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 1, 5, 4, 0, 8, 7, 3, 9, 2])>

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[-0.22,  1.49,  0.69],
       [ 0.27, -0.2 , -0.66],
       [ 3.26, -0.9 , -1.39],
       [ 1.37, -0.91,  1.24],
       [ 2.06,  0.09,  1.1 ],
       [ 0.56, -0.65,  0.99],
       [-1.04,  0.91,  0.48],
       [ 0.05,  0.52,  0.15],
       [-0.22, -0.68, -1.4 ],
       [ 0.78,  0.38,  1.  ]], dtype=float32)>

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([7, 5, 6, 3, 0, 0, 6, 1, 6, 1], dtype=int64)>

## 索引和切片

### reshape

In [126]:
a = tf.range(9)
a = tf.reshape(a,shape=(3,3))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [130]:
a = tf.range(9)
a = tf.reshape(a,shape=(3,3))
a
a[:1]
a[::-1]
a[:,:2]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 1, 2]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [3, 4],
       [6, 7]])>

In [133]:
a = tf.range(9)
a = tf.reshape(a,shape=(1,1,3,3))
a
a[...,1]
a[0,...,1]


<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]])>

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 4, 7]]])>

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 4, 7]])>

### transpose

In [150]:
a = tf.range(24)
a = tf.reshape(a,shape=(2,3,4))
a
tf.transpose(a)
tf.transpose(a,perm=[1,2,0])

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])>

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])>

### tf.expand_dims

In [151]:
a = tf.range(24)
a = tf.reshape(a,shape=(2,3,4))
a
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

<tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]],


       [[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])>

### tf.squeeze

In [152]:
a = tf.range(24)
a = tf.reshape(a,shape=(1,2,3,4))
a
tf.squeeze(a)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])>

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

### gather

In [141]:
a = tf.range(64)
a = tf.reshape(a,shape=(4,4,4))
a
idx=tf.convert_to_tensor([1,0,3])
tf.gather(a,indices=idx,axis=2)

<tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])>

<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[ 1,  0,  3],
        [ 5,  4,  7],
        [ 9,  8, 11],
        [13, 12, 15]],

       [[17, 16, 19],
        [21, 20, 23],
        [25, 24, 27],
        [29, 28, 31]],

       [[33, 32, 35],
        [37, 36, 39],
        [41, 40, 43],
        [45, 44, 47]],

       [[49, 48, 51],
        [53, 52, 55],
        [57, 56, 59],
        [61, 60, 63]]])>

### tf.gather_nd（select_index）

In [145]:
a = tf.range(27)
a = tf.reshape(a,shape=(3,3,3))
a
tf.gather_nd(a,[0])
tf.gather_nd(a,[0,1])
tf.gather_nd(a,[[0,1]])

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 4, 5]])>

### tf.boolean_mask (mask_select)

In [146]:
a = tf.range(27)
a = tf.reshape(a,shape=(3,3,3))
a
tf.boolean_mask(a,[False,True,True])

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

## boardingcast

### tf.broadcast_to

In [185]:
a = tf.ones([2,2,2])
b = tf.ones([2,1])
a
b
tf.broadcast_to(b,[2,2,3])

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

# 高级api

### concat

In [154]:
a = tf.ones([2,3])
b = tf.ones([3,3])
tf.concat((a,b),axis=0)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### stack

In [157]:
a = tf.ones([2,3])
b = tf.ones([2,3])
tf.stack((a,b),axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

### unstack

In [159]:
a = tf.range(9)
a = tf.reshape(a,shape=(3,3))
a
tf.unstack(a,axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 7, 8])>]

### split

In [160]:
a = tf.range(16)
a = tf.reshape(a,shape=(4,4))
a
tf.split(a,2,axis=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])>

[<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])>]

## 填充与复制

### pad

In [190]:
a = tf.ones([3,3])
tf.pad(a,paddings=[[0,1],[1,0]])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

### tile

In [201]:
a = tf.range(3)
a = tf.reshape(a,[1,-1])
a.shape
tf.tile(a,[3,2])

TensorShape([1, 3])

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])>

## 张量限幅

### maxmium,minmium

In [209]:
a = tf.range(9)
a = tf.reshape(a,[3,-1])
a = tf.random.shuffle(a)
a
b = tf.random.uniform([3,3],0,10,dtype=tf.int32)
b
tf.maximum(a,b)
tf.minimum(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 3, 8],
       [6, 7, 7],
       [3, 1, 3]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 4, 8],
       [6, 7, 8],
       [3, 1, 3]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 5],
       [6, 7, 7],
       [0, 1, 2]])>

### clip_by_value

In [212]:
a = tf.random.uniform([3,3],0,20,dtype=tf.int32)
a
tf.clip_by_value(a,5,15)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 14,  7],
       [ 6,  2, 19],
       [ 2, 15,  0]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 14,  7],
       [ 6,  5, 15],
       [ 5, 15,  5]])>

### clip_by_norm

In [223]:
a = tf.range(9.)
a = tf.reshape(a,[3,-1])
a
tf.norm(a)
tf.clip_by_norm(a,clip_norm=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

<tf.Tensor: shape=(), dtype=float32, numpy=14.282857>

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.  , 0.21, 0.42],
       [0.63, 0.84, 1.05],
       [1.26, 1.47, 1.68]], dtype=float32)>

In [219]:
a = tf.random.normal([2,2],mean=10)
a
tf.norm(a)
tf.clip_by_norm(a,15)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.65, 10.69],
       [ 9.97, 10.43]], dtype=float32)>

<tf.Tensor: shape=(), dtype=float32, numpy=20.883732>

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.65, 7.68],
       [7.16, 7.49]], dtype=float32)>

### tf.clip_by_global_norm

## 高阶操作

### where

In [226]:
a = tf.random.normal([3,3])
a
a>0
tf.where(a>0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.19,  0.21, -0.48],
       [ 1.78,  0.15,  0.02],
       [-0.82,  0.26, -1.58]], dtype=float32)>

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True, False]])>

<tf.Tensor: shape=(6, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 1]], dtype=int64)>

### tf.scatter_nd

### tf.meshgrid

In [228]:
x = tf.linspace(0.,1,10)
y = tf.linspace(0.,1,10)
tf.meshgrid(x,y)

[<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ],
        [0.  , 0.11, 0.22, 0.33, 0.44, 0.56, 0.67, 0.78, 0.89, 1.  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
        [0.22, 0.22, 0.22, 0.22, 

In [232]:
a = [1,2,3,4]
b = lambda x:x
b(3)

3

# math

In [179]:
a = tf.random.shuffle(tf.range(10))
a
tf.math.top_k(a,k=3)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 6, 8, 5, 4, 1, 3, 9, 7, 2])>

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 8, 7])>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 2, 8])>)

# 数据统计

In [166]:
a = tf.random.normal([3,3])
a
tf.reduce_sum(a)
tf.reduce_mean(a)
tf.reduce_max(a)
tf.norm(a)
tf.argmax(a)
tf.argmin(a,axis=1)
tf.argsort(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.46,  1.61,  0.52],
       [ 1.97,  0.6 , -1.04],
       [ 2.43, -0.05, -0.3 ]], dtype=float32)>

<tf.Tensor: shape=(), dtype=float32, numpy=6.206998>

<tf.Tensor: shape=(), dtype=float32, numpy=0.68966645>

<tf.Tensor: shape=(), dtype=float32, numpy=2.428205>

<tf.Tensor: shape=(), dtype=float32, numpy=3.7917385>

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 0, 0], dtype=int64)>

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 2], dtype=int64)>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [2, 1, 0],
       [2, 1, 0]])>

### equal

In [171]:
a = tf.random.uniform([3,3],0,2,dtype=tf.int64)
b = tf.random.uniform([3,3],0,2,dtype=tf.int64)
a
b
tf.equal(a,b)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 1],
       [1, 0, 1],
       [1, 1, 1]], dtype=int64)>

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 0]], dtype=int64)>

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False,  True,  True],
       [ True,  True, False],
       [False, False, False]])>

### unique

In [173]:
a = tf.random.uniform([10,],0,5,dtype=tf.int64)
a
tf.unique(a) # 数据1维

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 2, 1, 0, 0, 0, 0, 4, 1, 0], dtype=int64)>

Unique(y=<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 1, 0, 4], dtype=int64)>, idx=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 1, 2, 2, 2, 2, 3, 1, 2])>)

## sort

In [178]:
a = tf.random.shuffle(tf.range(10))
a
tf.sort(a,direction='DESCENDING')
tf.argsort(a,direction='ASCENDING')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 6, 3, 0, 2, 5, 8, 9, 4, 1])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 9, 4, 2, 8, 5, 1, 0, 6, 7])>

# network

### onehot

In [101]:
out = tf.random.normal([4,10])
out
y = tf.random.uniform([4,],0,10,dtype=tf.int64)
y
y = tf.one_hot(y,depth=10)
y
loss = tf.keras.losses.mse(y,out)
loss
loss = tf.reduce_mean(loss) # Computes the mean of elements across dimensions of a tensor.
loss


<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[ 0.97,  0.99,  1.18,  1.13,  0.52,  1.35,  0.38, -1.69,  1.33,
        -2.5 ],
       [ 0.5 ,  0.16,  0.94, -0.26, -1.95,  0.77,  1.18, -0.57, -1.31,
        -1.01],
       [ 0.49, -0.59,  0.06,  0.49, -0.41,  0.36,  0.47, -0.1 , -0.1 ,
         0.05],
       [ 2.  , -0.31,  0.65,  0.05,  0.78,  0.69, -0.76,  0.79,  0.25,
         0.37]], dtype=float32)>

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 8, 7, 9], dtype=int64)>

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.67, 1.36, 0.26, 0.73], dtype=float32)>

<tf.Tensor: shape=(), dtype=float32, numpy=1.0047851>

In [102]:
help(tf.reduce_mean)

Help on function reduce_mean in module tensorflow.python.ops.math_ops:

reduce_mean(input_tensor, axis=None, keepdims=False, name=None)
    Computes the mean of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    entry in `axis`. If `keepdims` is true, the reduced dimensions
    are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    x = tf.constant([[1., 1.], [2., 2.]])
    tf.reduce_mean(x)  # 1.5
    tf.reduce_mean(x, 0)  # [1.5, 1.5]
    tf.reduce_mean(x, 1)  # [1.,  2.]
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      axis: The dimensions to reduce. If `None` (the default), reduces all
        dimensions. Must be in the range `[-rank(input_tensor),
        rank(input_tenso

## layer

In [110]:
net = tf.keras.layers.Dense(10)
net.build((2,8))
net.kernel.shape
net.bias.shape

TensorShape([8, 10])

TensorShape([10])

## embedding

In [116]:
x_train = tf.random.uniform([2,4],0,10,dtype=tf.int64)
x_train

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[6, 7, 6, 9],
       [4, 6, 5, 0]], dtype=int64)>

In [120]:
emb = tf.keras.layers.Embedding(10,5)
emb(x_train)


<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[-0.02,  0.02,  0.02,  0.04, -0.03],
        [ 0.04,  0.01, -0.  ,  0.02, -0.05],
        [-0.02,  0.02,  0.02,  0.04, -0.03],
        [ 0.04, -0.  ,  0.  , -0.01, -0.04]],

       [[-0.04,  0.03, -0.05,  0.01,  0.05],
        [-0.02,  0.02,  0.02,  0.04, -0.03],
        [-0.  ,  0.03,  0.  ,  0.03, -0.  ],
        [-0.03, -0.04, -0.02,  0.  ,  0.03]]], dtype=float32)>

### Conv2d

In [121]:
input1 = tf.Variable(tf.constant(1.0, shape=[1, 1, 5, 5]))
filter1 = tf.Variable(tf.constant(1.0, shape=[3, 3, 1, 1]))
tf.nn.conv2d(input=input1,filters=filter1,strides=[1,1,1,1],padding="SAME",data_format="NCHW")

<tf.Tensor: shape=(1, 1, 5, 5), dtype=float32, numpy=
array([[[[4., 6., 6., 6., 4.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [4., 6., 6., 6., 4.]]]], dtype=float32)>

In [125]:
x = tf.Variable(tf.constant(1.0, shape=[2, 5, 5, 3]))
net = tf.keras.layers.Conv2D(5,kernel_size=3)
net(x).shape

TensorShape([2, 3, 3, 5])

# freetest

In [83]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 58us/sample - loss: 0.2990 - accuracy: 0.9125
Epoch 2/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.1490 - accuracy: 0.9552
Epoch 3/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.1098 - accuracy: 0.9667
Epoch 4/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.0915 - accuracy: 0.9717
Epoch 5/5
60000/60000 [==============================] - 3s 52us/sample - loss: 0.0762 - accuracy: 0.9760


10000/10000 - 1s - loss: 0.0742 - accuracy: 0.9757


[0.07416248116875067, 0.9757]

In [11]:
a = tf.constant([1,2,3])
a
a.shape
a.dtype
a.numpy

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

TensorShape([3])

tf.int32

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>>

In [15]:
tf.ones((4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.random.normal(shape=(3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.61,  1.02,  0.12],
       [ 1.2 , -0.81, -0.36],
       [ 0.85,  1.25, -0.23]], dtype=float32)>

In [22]:
tf.random.uniform(shape=(3,3),minval=0,maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.62, 2.68, 8.97],
       [7.3 , 6.13, 0.05],
       [1.63, 9.63, 1.77]], dtype=float32)>

In [30]:
tf.random.uniform(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.2 , 0.65, 0.31],
       [0.34, 0.97, 0.94],
       [0.72, 0.66, 0.65]], dtype=float32)>

In [43]:
# tf.random_normal([1,1,5,1])
tf.Variable([1,1,5,1])

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 1, 5, 1])>

In [31]:
help(tf.nn.conv2d)

Help on function conv2d_v2 in module tensorflow.python.ops.nn_ops:

conv2d_v2(input, filters, strides, padding, data_format='NHWC', dilations=None, name=None)
    Computes a 2-D convolution given 4-D `input` and `filters` tensors.
    
    Given an input tensor of shape `[batch, in_height, in_width, in_channels]`
    and a filter / kernel tensor of shape
    `[filter_height, filter_width, in_channels, out_channels]`, this op
    performs the following:
    
    1. Flattens the filter to a 2-D matrix with shape
       `[filter_height * filter_width * in_channels, output_channels]`.
    2. Extracts image patches from the input tensor to form a *virtual*
       tensor of shape `[batch, out_height, out_width,
       filter_height * filter_width * in_channels]`.
    3. For each patch, right-multiplies the filter matrix and the image patch
       vector.
    
    In detail, with the default NHWC format,
    
        output[b, i, j, k] =
            sum_{di, dj, q} input[b, strides[1] * i + d

In [72]:
input2 = tf.Variable(tf.constant(1.0, shape=[1, 5, 5, 1]))
filter2 = tf.Variable(tf.constant([-1.0, 0, 0, -1], shape=[2, 2, 1, 1]))
op2 = tf.nn.conv2d(input2, filter2, strides=[1, 2, 2, 1], padding='SAME')
input2
filter2
op2


<tf.Variable 'Variable:0' shape=(1, 5, 5, 1) dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[-1.]],

        [[ 0.]]],


       [[[ 0.]],

        [[-1.]]]], dtype=float32)>

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-2.],
         [-2.],
         [-1.]],

        [[-2.],
         [-2.],
         [-1.]],

        [[-1.],
         [-1.],
         [-1.]]]], dtype=float32)>

In [77]:
input1 = tf.Variable(tf.constant(1.0, shape=[1, 1, 5, 5]))
filter1 = tf.Variable(tf.constant(1.0, shape=[3, 3, 1, 1]))
# tf.nn.conv2d(input, filters, strides, padding, data_format='NHWC', dilations=None, name=None)
# tf.nn.conv2d(input=input1,filters=filter1,strides=1,padding="VALID")
tf.nn.conv2d(input=input1,filters=filter1,strides=[1,1,1,1],padding="SAME",data_format="NCHW")

<tf.Tensor: shape=(1, 1, 5, 5), dtype=float32, numpy=
array([[[[4., 6., 6., 6., 4.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [4., 6., 6., 6., 4.]]]], dtype=float32)>

In [63]:
input1

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [61]:
a = tf.constant([1,2,3,4],dtype=tf.float32)
tf.reshape(a,[2,2,1,-1])
tf.reshape(tf.constant([3,3,1,1],dtype=tf.float32),[2,2,1,-1])

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[2.]]],


       [[[3.]],

        [[4.]]]], dtype=float32)>

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[3.]],

        [[3.]]],


       [[[1.]],

        [[1.]]]], dtype=float32)>

In [57]:
filter1 = tf.constant([[[[1]],
  [[2]]],

 [[[ 3]],
  [[4]]]],dtype=tf.float32)
filter1

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[2.]]],


       [[[3.]],

        [[4.]]]], dtype=float32)>

In [53]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a new `tf.Tensor` that has the same
    values as `tensor` in the same order, except with a new shape given by
    `shape`.
    
    >>> t1 = [[1, 2, 3],
    ...       [4, 5, 6]]
    >>> print(tf.shape(t1).numpy())
    [2 3]
    >>> t2 = tf.reshape(t1, [6])
    >>> t2
    <tf.Tensor: shape=(6,), dtype=int32,
      numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
    >>> tf.reshape(t2, [3, 2])
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
      array([[1, 2],
             [3, 4],
             [5, 6]], dtype=int32)>
    
    The `tf.reshape` does not change the order of or the total number of elements
    in the tensor, and so it can reuse the underlying data buffer. This makes it
    a fast operation independent of how big of a tensor it is operating on.
    
    >>> tf.reshape([1, 2, 3], [2, 2])
    Traceback (mos