In [1]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all' #默认为'last'

import numpy as np
import pandas as pd
import os
import sympy 
# import numpy.linalg as LA
from sympy import *
from matplotlib import pyplot as plt
%matplotlib inline
plt.rcParams['font.sans-serif']=['SimHei'] #指定默认字体 SimHei为黑体
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
sympy.init_printing(use_latex=True)
# x, y, z = symbols('x y z',real=True)

import torch
import scipy.linalg as la
import numpy.linalg as LA

np.set_printoptions(precision=2,suppress=True)

#Note that http urls will not be displayed. Only https are allowed inside the Iframe
from IPython.display import IFrame

# 强化学习

## 分类  
* 基于有模型
* 基于无模型  

## 因素
* 环境environment
* 观察observe
* 状态state
* 奖励reward
* 代理agent

## Q函数
* V价值$\pi(x)=argmax_a Q(s,a)$
* Q价值$Q(s,a)=r+\gamma max_{a\prime} Q(s\prime,a\prime)$
* 动作优势Q-V

### 马尔可夫随机过程

### 马尔可夫决策过程

## Q网络（价值网络）

### Q学习的问题

* 不能解决状态无限的问题
* 不能解决动作无限的问题

## 策略梯度网络

## AC模型

## A3C模型


## api


In [7]:
a = np.arange(16).reshape(4, 4)
a
x = zip(*a)
x
for x1 in x:
    x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

(0, 4, 8, 12)

(1, 5, 9, 13)

(2, 6, 10, 14)

(3, 7, 11, 15)

In [17]:
np.random.randn(5)

array([ 0.59,  0.25, -1.02, -0.49,  1.68])

In [19]:
import torchvision

In [31]:
m = np.array([[1,2],[3,4]], int)
m
# array([[1, 2],
#    [3, 4]])
np.rot90(m)
# array([[2, 4],
#    [1, 3]])
np.rot90(m, 2)
# array([[4, 3],
#    [2, 1]])
np.rot90(m, -1)
m = np.arange(8).reshape((2,2,2))
m
np.rot90(m, 1, (1,2))
# array([[[1, 3],
# [0, 2]],
#    [[5, 7],
# [4, 6]]])

array([[1, 2],
       [3, 4]])

array([[2, 4],
       [1, 3]])

array([[4, 3],
       [2, 1]])

array([[3, 1],
       [4, 2]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[1, 3],
        [0, 2]],

       [[5, 7],
        [4, 6]]])

In [30]:
# Rotate an array by 90 degrees in the plane specified by axes.
# Rotation direction is from the first towards the second axis.
m
np.rot90(m, 1, (0,1))
np.rot90(m, 1, (1,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[2, 3],
        [6, 7]],

       [[0, 1],
        [4, 5]]])

array([[[1, 3],
        [0, 2]],

       [[5, 7],
        [4, 6]]])

In [20]:
help(np.rot90)

Help on function rot90 in module numpy:

rot90(m, k=1, axes=(0, 1))
    Rotate an array by 90 degrees in the plane specified by axes.
    
    Rotation direction is from the first towards the second axis.
    
    Parameters
    ----------
    m : array_like
        Array of two or more dimensions.
    k : integer
        Number of times the array is rotated by 90 degrees.
    axes: (2,) array_like
        The array is rotated in the plane defined by the axes.
        Axes must be different.
    
        .. versionadded:: 1.12.0
    
    Returns
    -------
    y : ndarray
        A rotated view of `m`.
    
    See Also
    --------
    flip : Reverse the order of elements in an array along the given axis.
    fliplr : Flip an array horizontally.
    flipud : Flip an array vertically.
    
    Notes
    -----
    rot90(m, k=1, axes=(1,0)) is the reverse of rot90(m, k=1, axes=(0,1))
    rot90(m, k=1, axes=(1,0)) is equivalent to rot90(m, k=-1, axes=(0,1))
    
    Examples
    --------

In [43]:
a = np.array([[1,2],[3,4]], int)
a
for i in range(1,4):
    b = np.rot90(a,k=i)
    b
    c = np.fliplr(b)
    c
    

array([[1, 2],
       [3, 4]])

array([[2, 4],
       [1, 3]])

array([[4, 2],
       [3, 1]])

array([[4, 3],
       [2, 1]])

array([[3, 4],
       [1, 2]])

array([[3, 1],
       [4, 2]])

array([[1, 3],
       [2, 4]])

In [38]:
help(np.fliplr)

Help on function fliplr in module numpy:

fliplr(m)
    Flip array in the left/right direction.
    
    Flip the entries in each row in the left/right direction.
    Columns are preserved, but appear in a different order than before.
    
    Parameters
    ----------
    m : array_like
        Input array, must be at least 2-D.
    
    Returns
    -------
    f : ndarray
        A view of `m` with the columns reversed.  Since a view
        is returned, this operation is :math:`\mathcal O(1)`.
    
    See Also
    --------
    flipud : Flip array in the up/down direction.
    rot90 : Rotate array counterclockwise.
    
    Notes
    -----
    Equivalent to m[:,::-1]. Requires the array to be at least 2-D.
    
    Examples
    --------
    >>> A = np.diag([1.,2.,3.])
    >>> A
    array([[1.,  0.,  0.],
           [0.,  2.,  0.],
           [0.,  0.,  3.]])
    >>> np.fliplr(A)
    array([[0.,  0.,  1.],
           [0.,  2.,  0.],
           [3.,  0.,  0.]])
    
    >>> A = np.ran

In [37]:
np.set_printoptions(precision=4,suppress=True)
a = np.array([
    0.01185771, 0.01185771, 0.01185771, 0.01383399, 0.01185771, 0., 0.01383399,
    0.01185771, 0.01185771, 0.01185771, 0.01185771, 0.01185771, 0.01383399,
    0.01185771, 0.01383399, 0.01383399, 0.01185771, 0.01185771, 0.01185771,
    0.01185771, 0.01383399, 0.01383399, 0.01185771, 0.01185771, 0.01185771,
    0.01383399, 0.01185771, 0.01185771, 0.01185771, 0.01185771, 0.01185771,
    0.01185771, 0.01185771, 0.01185771, 0.01185771, 0.01185771, 0.01185771,
    0.01185771, 0.01185771, 0.01185771, 0.01383399, 0.01383399, 0.01185771,
    0.01383399, 0.01185771, 0.01383399, 0.01185771, 0.01383399, 0.01383399,
    0.01185771, 0.01185771, 0.01383399, 0.01185771, 0.01383399, 0.01383399,
    0.01383399, 0.01185771, 0.01383399, 0.01185771, 0.01185771, 0.01185771,
    0.01185771, 0.01383399, 0.01185771, 0.01383399, 0.01185771, 0.01185771,
    0.01383399, 0.01185771, 0.01383399, 0.01383399, 0.01185771, 0.01185771,
    0.01383399, 0.01185771, 0.01185771, 0.01185771, 0.01383399, 0.01185771,
    0.01185771, 0.01185771
]).reshape(9, 9)
a

array([[0.0119, 0.0119, 0.0119, 0.0138, 0.0119, 0.    , 0.0138, 0.0119,
        0.0119],
       [0.0119, 0.0119, 0.0119, 0.0138, 0.0119, 0.0138, 0.0138, 0.0119,
        0.0119],
       [0.0119, 0.0119, 0.0138, 0.0138, 0.0119, 0.0119, 0.0119, 0.0138,
        0.0119],
       [0.0119, 0.0119, 0.0119, 0.0119, 0.0119, 0.0119, 0.0119, 0.0119,
        0.0119],
       [0.0119, 0.0119, 0.0119, 0.0119, 0.0138, 0.0138, 0.0119, 0.0138,
        0.0119],
       [0.0138, 0.0119, 0.0138, 0.0138, 0.0119, 0.0119, 0.0138, 0.0119,
        0.0138],
       [0.0138, 0.0138, 0.0119, 0.0138, 0.0119, 0.0119, 0.0119, 0.0119,
        0.0138],
       [0.0119, 0.0138, 0.0119, 0.0119, 0.0138, 0.0119, 0.0138, 0.0138,
        0.0119],
       [0.0119, 0.0138, 0.0119, 0.0119, 0.0119, 0.0138, 0.0119, 0.0119,
        0.0119]])

In [3]:
import copy

In [4]:
help(copy.deepcopy)

Help on function deepcopy in module copy:

deepcopy(x, memo=None, _nil=[])
    Deep copy operation on arbitrary Python objects.
    
    See the module's __doc__ string for more info.



# end 