In [49]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

/mnt/shared *(rw,sync,no_root_squash,no_subtree_check)
mount -t nfs -o proto=tcp,port=2049,nolock 192.168.10.107:/home/wenquanshan/Docker /mnt/Docker

mount -t nfs -o proto=tcp,port=2049,nolock 10.0.2.201:/home/hjimi/Docker /mnt/201

In [6]:
x = b'0abc'
x
[bin(a) for a in x]

['0b110000', '0b1100001', '0b1100010', '0b1100011']

In [23]:
np.float32.itemsize

<attribute 'itemsize' of 'numpy.generic' objects>

In [26]:
import numpy as np

# 定义一个NumPy数组
arr = np.array([1, 2, 3], dtype=np.int8)

# 获取数据类型的字节数
size = arr.dtype.itemsize

# 打印结果
print("数据类型所占空间大小：{} 字节".format(size))


数据类型所占空间大小：1 字节


In [32]:
import numpy as np

# 定义一个字符串
string_data = "Hello, World!"

# 将字符串转换为NumPy字符数组
array = np.array(list(string_data), dtype=np.dtype('S1'))
print(array.itemsize, array.dtype)
array2 = array.astype(np.uint8)
print(array2.itemsize)
# 打印结果
# print(array)
# a = array.tobytes()
# a


1 |S1


ValueError: invalid literal for int() with base 10: b'H'

In [34]:
import numpy as np

# 定义一个字符数组
char_array = np.array(['1', '2', '3', '4', '5'])

# 将字符数组转换为整型数组
int_array = char_array.astype(int)

# 打印结果
print(int_array)


[1 2 3 4 5]


In [35]:
import numpy as np

# 定义一个字符数组
char_array = np.array(['A', 'B', 'C', 'D', 'E'])

# 定义转换函数
convert_func = np.frompyfunc(ord, 1, 1)

# 将字符数组转换为整型数组
int_array = convert_func(char_array)

# 打印结果
print(int_array)


[65 66 67 68 69]


In [37]:
import torch

In [44]:
a = torch.Tensor([1,2,3])
# a
a.data
a.data_ptr()

94309967927360

In [19]:
int('11111111',2), int('1111111111111111',2), 0xFF, 0xFFFF

(255, 65535, 255, 65535)

In [10]:
chr(97)

'a'

In [3]:
k = 0xAB
k, bin(k)

(171, '0b10101011')

In [8]:
bin(255)

'0b11111111'

In [3]:
!nvidia-smi

Thu Apr  6 12:05:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN V      Off  | 00000000:04:00.0 Off |                  N/A |
| 28%   41C    P2    35W / 250W |   1242MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN V      Off  | 00000000:05:00.0 Off |                  N/A |
| 28%   

In [9]:
416*416

173056

In [3]:
x = np.arange(1024)
a = np.sin(x)
b = np.cos(x)
c = a + b
c
np.dot(a.T, b)

array([ 1.        ,  1.38177329,  0.49315059, ..., -0.9822334 ,
       -1.38686302, -0.51641718])

0.08633305630871865

In [8]:
4096/64

64.0

In [10]:
0x1800

6144

In [11]:
1024*6

6144

In [47]:
import torch
import torch.nn as nn

In [46]:
torch.nn.L1Loss?


In [50]:
# With square kernels and equal stride
m = nn.ConvTranspose2d(16, 33, 3, stride=2)
# non-square kernels and unequal stride and with padding
m = nn.ConvTranspose2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
x = torch.randn(20, 16, 50, 100)
y = m(x)
y.size()
# exact output size can be also specified as an argument
x = torch.randn(1, 16, 12, 12)
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)
h = downsample(x)
h.size()
output = upsample(h, output_size=input.size())
output.size()

torch.Size([20, 33, 93, 100])

torch.Size([1, 16, 6, 6])

torch.Size([1, 16, 12, 12])

In [78]:
x = torch.randn(1, 16, 128, 128)
downsample = nn.Conv2d(16, 16, 7, stride=2, padding=1)
upsample = nn.ConvTranspose2d(16, 16, 3, stride=4, padding=1, output_padding=3)
h = downsample(x)
h.size()
output = upsample(h)
output.size()

torch.Size([1, 16, 62, 62])

torch.Size([1, 16, 248, 248])

In [88]:
x = torch.randn(1, 1, 5, 5)
downsample = nn.Conv2d(1, 1, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=0)
upsample1 = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=0)
h = downsample(x)
h.size()
y = upsample(h)
y.size()
y1 = upsample1(h)
y1.size()
y
y1

torch.Size([1, 1, 3, 3])

torch.Size([1, 1, 5, 5])

torch.Size([1, 1, 5, 5])

tensor([[[[-0.3093, -0.3665, -0.2657, -0.2544, -0.1902],
          [-0.3924, -0.1280, -0.3535, -0.2466, -0.1745],
          [-0.3385, -0.4933, -0.3911, -0.4539, -0.2281],
          [-0.4653, -0.5214, -0.4226, -0.4689, -0.1859],
          [-0.4096, -0.4205, -0.1423, -0.0434, -0.1315]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

tensor([[[[2.3064e-01, 9.5724e-02, 1.9556e-01, 1.6054e-01, 1.3482e-01],
          [1.3070e-01, 2.2006e-01, 1.8396e-01, 4.3802e-01, 1.9692e-01],
          [2.5420e-01, 1.4615e-02, 2.9654e-01, 6.4069e-02, 1.6531e-01],
          [1.2809e-01, 2.3576e-01, 2.7536e-04, 1.3473e-01, 1.3475e-01],
          [3.1137e-01, 9.5796e-02, 9.6277e-02, 2.6620e-01, 8.7532e-02]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

In [98]:
x = torch.randn(1, 1, 6, 6)
down = nn.Conv2d(1, 1, 3, stride=2, padding=1)
up = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=0)
up1 = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=1)
up.weight = nn.Parameter(torch.ones_like(up.weight))
up1.weight = nn.Parameter(torch.ones_like(up1.weight))
up.bias = nn.Parameter(torch.ones_like(up.bias))
up1.bias = nn.Parameter(torch.ones_like(up1.bias))
h = down(x)
h.size()
y = up(h)
y.size()
y1 = up1(h)
y1.size()
y
y1


torch.Size([1, 1, 3, 3])

torch.Size([1, 1, 5, 5])

torch.Size([1, 1, 6, 6])

tensor([[[[ 1.1957,  0.7997,  0.6039,  0.8489,  1.2450],
          [ 0.9188,  0.2865,  0.3677,  0.0919,  0.7242],
          [ 0.7231,  0.4868,  0.7637,  0.2430,  0.4793],
          [ 1.0673,  0.0865,  0.0192, -1.1782, -0.1974],
          [ 1.3442,  0.5997,  0.2555, -0.4211,  0.3233]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

tensor([[[[ 1.1957,  0.7997,  0.6039,  0.8489,  1.2450,  1.2450],
          [ 0.9188,  0.2865,  0.3677,  0.0919,  0.7242,  0.7242],
          [ 0.7231,  0.4868,  0.7637,  0.2430,  0.4793,  0.4793],
          [ 1.0673,  0.0865,  0.0192, -1.1782, -0.1974, -0.1974],
          [ 1.3442,  0.5997,  0.2555, -0.4211,  0.3233,  0.3233],
          [ 1.3442,  0.5997,  0.2555, -0.4211,  0.3233,  0.3233]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

tensor([[[[-0.0772, -0.1619, -0.1059, -0.2029, -0.1024],
          [-0.1348,  0.0948, -0.1253, -0.2055, -0.0426],
          [-0.0886, -0.2985, -0.1193, -0.1115, -0.0872],
          [-0.1130,  0.2573,  0.0167, -0.5055, -0.1521],
          [-0.0946, -0.0511, -0.0871, -0.1885, -0.1062]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

tensor([[[[ 0.1168,  0.1964,  0.1589,  0.2481,  0.1537,  0.1658],
          [ 0.0830, -0.2058,  0.0734,  0.2096,  0.2153,  0.2744],
          [ 0.1334,  0.3287,  0.1785,  0.1696,  0.1314,  0.1244],
          [ 0.1096,  0.2929,  0.2999,  0.2693,  0.0451, -0.0067],
          [ 0.1422,  0.1017,  0.1313,  0.2259,  0.1593,  0.1762],
          [ 0.1485,  0.1264,  0.1114,  0.1566,  0.2066,  0.2759]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

In [83]:
x = torch.randn(1, 1, 5, 5)
downsample = nn.Conv2d(1, 1, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=0)
h = downsample(x)
h.size()
y = upsample(h)
y.size()

torch.Size([1, 1, 3, 3])

torch.Size([1, 1, 5, 5])

In [82]:
x
y

tensor([[[[-0.3256, -0.2951,  0.9024,  0.2518, -0.6083],
          [ 1.5094,  0.7742, -0.2906, -1.2123, -0.9252],
          [ 0.8520, -0.1239,  0.8412, -0.0914,  0.5549],
          [ 0.1946, -0.1306,  0.5278,  1.3719,  0.3391],
          [ 0.4267,  0.6061, -3.9008, -0.9503, -0.3829]]]])

tensor([[[[-0.2599, -0.1101, -0.1413, -0.0538, -0.0472, -0.2193],
          [-0.2117, -0.2307, -0.3049, -0.3312, -0.3098, -0.2938],
          [-0.2401, -0.3349, -0.3507, -0.2872, -0.3421, -0.1159],
          [-0.1578, -0.1600,  0.0201,  0.0229, -0.0311, -0.0585],
          [-0.1618,  0.0732,  0.0679, -0.0800, -0.0020, -0.2352],
          [-0.1761, -0.2416, -0.2030, -0.1791, -0.1949, -0.1427]]]],
       grad_fn=<SlowConvTranspose2DBackward>)